### ISSUE TITLE
date before first commit not last

### ISSUE THREAD

**Issue by handsomematt** [SilasX/git-upstage#2]
dating 5 minutes before the last commit seems weird, surely it makes a lot more sense to date 5 minutes before the first commit?

**Comment by SilasX** [comment]
Well, the idea is that you're upstaging them by finishing five minutes before they finished, not finishing five minutes before they started.  I mean, it makes sense also, but seems like an unnecessary reach.

**Comment by SilasX** [comment]
Closing per [comment](https://github.com/SilasX/git-upstage/issues/2#issuecomment-128470914).
